package org.gmake.studio;

import javax.swing.*;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeNode;
import javax.swing.tree.TreePath;
import java.awt.*;
import java.util.HashMap;

public class MainScreen {
	private JTree sprites;
	private HashMap<TreePath, Sprite> map = new HashMap<>();
	private JPanel panel1;
	private JButton new_sprite;
	private JButton new_pfile;
	private JButton new_game;
	private JPanel aaa;

	public MainScreen() {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
		sprites.setModel(new DefaultTreeModel(new DefaultMutableTreeNode("game")));
		sprites.setBackground(new Color(90, 90, 90));
		sprites.addTreeSelectionListener(e -> {
			$$$getRootComponent$$$().add(new GamePanel(map.get(e.getPath())), BorderLayout.CENTER);
		});
		aaa.setBackground(new Color(90, 90, 90));
		new_sprite.addActionListener(e -> {
			String id = JOptionPane.showInputDialog("Enter sprite ID, used in game");
			String clazz = JOptionPane.showInputDialog("Enter class name for new sprite");
			Sprite spr = new Sprite(id, clazz);
			((DefaultMutableTreeNode) sprites.getModel().getRoot()).add(spr.node);
			map.put(new TreePath(((DefaultMutableTreeNode) spr.node).getPath()), spr);
			sprites.repaint();
		});
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		panel1 = new JPanel();
		panel1.setLayout(new BorderLayout(0, 0));
		panel1.setMinimumSize(new Dimension(600, 400));
		panel1.setPreferredSize(new Dimension(800, 600));
		sprites = new JTree();
		sprites.setLargeModel(false);
		sprites.setMinimumSize(new Dimension(150, 100));
		sprites.setPreferredSize(new Dimension(150, 600));
		sprites.setRootVisible(true);
		sprites.setShowsRootHandles(true);
		panel1.add(sprites, BorderLayout.WEST);
		aaa = new JPanel();
		aaa.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
		panel1.add(aaa, BorderLayout.NORTH);
		new_sprite = new JButton();
		new_sprite.setText("New Sprite");
		aaa.add(new_sprite);
		new_pfile = new JButton();
		new_pfile.setText("New Python File");
		aaa.add(new_pfile);
		new_game = new JButton();
		new_game.setText("New Game");
		aaa.add(new_game);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return panel1;
	}
}
