package org.gmake.studio;

import javax.swing.*;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import java.awt.*;

public class MainScreen {
	private JTree sprites;
	private JPanel panel1;
	JMenuBar mb;

	public MainScreen() {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
		sprites.setModel(new DefaultTreeModel(new DefaultMutableTreeNode("game")));
		sprites.setBackground(new Color(90, 90, 90));
		mb = new JMenuBar();
		JMenu file = new JMenu("File");
		JMenu _new = new JMenu("New");
		_new.add("Python File");
		_new.add("Game");
		file.add(_new);
		mb.add(file);
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		panel1 = new JPanel();
		panel1.setLayout(new BorderLayout(0, 0));
		panel1.setMinimumSize(new Dimension(600, 400));
		panel1.setPreferredSize(new Dimension(800, 600));
		sprites = new JTree();
		sprites.setLargeModel(false);
		sprites.setMinimumSize(new Dimension(73, 54));
		sprites.setPreferredSize(new Dimension(73, 600));
		sprites.setRootVisible(true);
		sprites.setShowsRootHandles(true);
		panel1.add(sprites, BorderLayout.WEST);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return panel1;
	}
}
